### ISSUE TITLE
add a version with lstchain

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/jh-session-images#1]

**Comment by Ph0tonic** [comment]
Hi, could you clarify your issue ? Shall we add `lstchain` to existing images ? And if so, to which one ?

**Comment by volodymyrss** [comment]
Some of the images here have lstchain already, right?

**Comment by Ph0tonic** [comment]
Only the `gammapy-noir`.

**Comment by volodymyrss** [comment]
Ok. This issues was for me to add it. This should be ok, we can move to other images if needed.
