### ISSUE TITLE
merge with noir session image from  https://github.com/cta-epfl/jh-session-noir

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/jh-session-images#7]
noir session image from https://github.com/cta-epfl/jh-session-noir should be one of the options in this repo.

I just saved in https://github.com/cta-epfl/jh-session-noir what I had and what is now functional.

Note that singularity artifact is also needed in all images.

Could you please do it?

**Comment by Ph0tonic** [comment]
You did this yesterday
